installPlugins:
    - kubernetes:3937.vd7b_82db_e347b_
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.0
    - configuration-as-code:1647.ve39ca_b_829b_42
    - gitlab-plugin:1.7.14
    - blueocean:1.27.4
controller:
    serviceType: LoadBalancer
    targetPort: 8080
