apiVersion: v1
kind: Pod
spec:
  containers:
  - name: flaskapp-docker-helm-build
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run
      name: docker-sock
  volumes:
  - name: docker-sock
    emptyDir: {}
